version: "3.3"

services:
  nats:
    image: nats
    container_name: nats
    networks:
      - main-network

  mongo:
    image: bitnami/mongodb:latest
    container_name: db
    restart: always
    env_file: docker-compose.env
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb/:/data/db
    networks:
      - main-network

networks:
  main-network:
    external: true
